[package]
name = "anchor_project"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.28.0"
ahash = "=0.7.6"
bumpalo = "=3.12.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[patch.crates-io]
ahash = { path = "../../../../../local_crates/aHash" }
